server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka 
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /weisg
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: weisg-microcloud
  company.name: www.weisg.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$     